### ISSUE TITLE
你的这个规则里的很多adguard home是识别不了的.而且adguard home跑一百万条规则真的没这个必要.

### ISSUE THREAD

**Issue by Karmylr** [BlueSkyXN/AdGuardHomeRules#1]

**Comment by Karmylr** [comment]
只需要你这个规则所包含的anti ad就足够了.而且你的规则不一定能做到包含的所有规则更新后自己也及时更新.比如anti-ad更新频率就非常快

**Comment by BlueSkyXN** [comment]
已针对部分问题做出修复：

移除无效规则
增加定期更新规则组
调整规则组成

如果不想要这么多规则，可以直接选取其他作者的作品，这样更方便
大部分规则都基本够用，只不过部分网站需要定制规则
