### ISSUE TITLE
规则误杀

### ISSUE THREAD

**Issue by cike-567** [BlueSkyXN/AdGuardHomeRules#11]
误杀规则：动漫&漫画网站定制规则（https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/manhua-plus.txt）

误杀网站：bbs.kafan.cn

**Comment by BlueSkyXN** [comment]
plus规则是非常强力的，针对的是频繁更换广告域名的，非必要不开启
另外这个规则没有 bbs.kafan.cn 啊，是他们用的CNAME有问题？

**Comment by cike-567** [comment]
adguardhome 是这样显示的，应该是 ||fun^ 这个规则。

**Comment by cike-567** [comment]
adguardhome 是这样显示的，我记得是匹配上了某个规则

**Comment by BlueSkyXN** [comment]
> bbs.kafan.cn

bbs.kafan.cn
未在您的筛选列表中找到

cname: bbs.kafan.cn.cdn.fun

自己检查是不是把fun 禁用了，已知manhua-plus.txt禁用了fun域名，基本逻辑不难理解
