### ISSUE TITLE
大佬可以出一个如何抓广告的教程吗

### ISSUE THREAD

**Issue by sujiuer5201314** [BlueSkyXN/AdGuardHomeRules#17]

**Comment by BlueSkyXN** [comment]
1,   Chrome浏览器 Ublock插件
2，浏览器F12控制台（简单）
3，wireshark/suite抓包（太麻烦，一般不用）
4，iOS Shadowrocket抓包（开启HTTPS解密后可见URL，慢慢找就行了，同时访问日志的域名看一眼就知道哪些有问题了）

**Comment by BlueSkyXN** [comment]
> _No description provided._

如果要DIY的话，推荐2和4，3学习成本高，1不太好用
手机上比较方便的手动屏蔽也可以使用via、alook浏览器以及adguard插件
