### ISSUE TITLE
我想知道这东西怎么用？

### ISSUE THREAD

**Issue by Lu-huibin** [BlueSkyXN/AdGuardHomeRules#19]
大佬，这个广告拦截器怎么用？有教程么，或者readme文件也行。

**Comment by BlueSkyXN** [comment]
ADGUARDHOME  https://adguard.com/en/adguard-home/overview.html
或者任意广告拦截器插件、浏览器

> 大佬，这个广告拦截器怎么用？有教程么，或者readme文件也行。
