### ISSUE TITLE
不支持IPv6 Only的VPS吗？

### ISSUE THREAD

**Issue by rookie-io** [BlueSkyXN/AdGuardHomeRules#2]
如题：
在EUServ的Free VPS上，无法添加规则。
也试了下cdn.000714.xyz的地址，也不行；不清楚是怎么个情况。
![adguard](https://user-images.githubusercontent.com/73265038/115977343-9ef75f00-a5a9-11eb-88c3-1f372cd9b30b.png)

https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/all.txt
https://cdn.000714.xyz/BlueSkyXN/AdGuardHomeRules/master/all.txt

**Comment by BlueSkyXN** [comment]
GIThub不支持IPV6，与我无关，Github的锅

**Comment by BlueSkyXN** [comment]
建议自己学会套V4，可以用NAT64或者CF-WARP
