### ISSUE TITLE
QQ空间正常图片被屏蔽

### ISSUE THREAD

**Issue by Sanluli36li** [BlueSkyXN/AdGuardHomeRules#20]
网页的图片是来自这个域名，但是白名单过滤这条域名之后手机还是刷不出来
`a1.qpic.cn`
网页的表情
`qzonestyle.gtimg.cn`

手Q的不好拿图片链接 干脆就直接去掉主域名的屏蔽了
加了这个规则之后正常了
```
@@||gtimg.cn^
@@||qpic.cn^
```

**Comment by BlueSkyXN** [comment]
> 网页的图片是来自这个域名，但是白名单过滤这条域名之后手机还是刷不出来 `a1.qpic.cn` 网页的表情 `qzonestyle.gtimg.cn`
> 
> 手Q的不好拿图片链接 干脆就直接去掉主域名的屏蔽了 加了这个规则之后正常了
> 
> ```
> @@||gtimg.cn^
> @@||qpic.cn^
> ```

主要是我在小火箭环境下未能复现这个问题，你是用哪种方式使用ADG的
