### ISSUE TITLE
b站中的广告屏蔽

### ISSUE THREAD

**Issue by baimaosama** [BlueSkyXN/AdGuardHomeRules#21]
b站中带有广告图标的内容能不能屏蔽掉。网页上使用adblock插件是可以屏蔽广告内容，但是关闭adblock后，依然会显示。手机上更是重灾区，两个视频一个广告。痛苦不堪

**Comment by BlueSkyXN** [comment]
> b站中带有广告图标的内容能不能屏蔽掉。网页上使用adblock插件是可以屏蔽广告内容，但是关闭adblock后，依然会显示。手机上更是重灾区，两个视频一个广告。痛苦不堪

也需要你需要使用小火箭的模块，但是我记得也不一定完全靠谱
