### ISSUE TITLE
quark网盘被误杀了

### ISSUE THREAD

**Issue by kettly1260** [BlueSkyXN/AdGuardHomeRules#23]
pan.quark.cn

规则
||ad.
BlueSkyXN-all

**Comment by BlueSkyXN** [comment]
> pan.quark.cn
> 
> 规则 ||ad. BlueSkyXN-all

解放了ok.txt和
补充规则skyrules.txt
了吗
阿里系的有的cname带了ad域名

**Comment by kettly1260** [comment]
> > pan.quark.cn
> > 规则 ||ad. BlueSkyXN-all
> 
> 解放了ok.txt和 补充规则skyrules.txt 了吗 阿里系的有的cname带了ad域名

重新添加ok确实好了
