### ISSUE TITLE
大佬您好，关于Koofr云盘

### ISSUE THREAD

**Issue by dgggh-56** [BlueSkyXN/AdGuardHomeRules#25]
我想要Koofr永久一tb，但是试了好久都不能成功，能否请您帮助一下我呢

**Comment by BlueSkyXN** [comment]
和本库无关，先close噢，有问题联系方式联系我

**Comment by dgggh-56** [comment]
> 我想要Koofr永久一tb，但是试了好久都不能成功，能否请您帮助一下我呢
