### ISSUE TITLE
关于 data.bilibili.com 黑名单

### ISSUE THREAD

**Issue by CHENBIN99** [BlueSkyXN/AdGuardHomeRules#26]
域名：data.bilibili.com

这个域名在观看bilibili的时候会一直请求，比其他域名高了两个数量级。这个域名屏蔽的原因是什么，貌似屏蔽这个域名会影响一些正常功能

**Comment by BlueSkyXN** [comment]
> data.bilibili.com

 根据目前已知的信息，有以下可能性

1. 移动端操作log汇报点 参考 [野生文档ISSUE](https://github.com/SocialSisterYi/bilibili-API-collect/issues/755)
2. 未知的隐私收集 [https://fuckwall.cc/posts/bilibili-live-gift-check](https://fuckwall.cc/posts/bilibili-live-gift-check)
3. "框架图” [https://www.mesalab.cn/f/article/detail?id=206](https://www.mesalab.cn/f/article/detail?id=206)

根据我实践来看，屏蔽这个并没有发现有什么异常，建议在本地拦截掉这个域名（比如Windows的Hosts/浏览器插件、iOS的ShadowRocket/Adguard、安装的Clash/Adguard）

类似的还有 

1. dataflow.bilibili.com
2. cm.bilibili.com

等没明显功能，杀了没影响的

既不会影响哔哩哔哩客户端和网页版使用，但是却在高配请求

要不要放行自己考虑，可自己加白

**Comment by BlueSkyXN** [comment]
> > data.bilibili.com
> 
> 根据目前已知的信息，有以下可能性
> 
> 1. 移动端操作log汇报点 参考 [野生文档ISSUE](https://github.com/SocialSisterYi/bilibili-API-collect/issues/755)
> 2. 未知的隐私收集 https://fuckwall.cc/posts/bilibili-live-gift-check
> 3. "框架图” https://www.mesalab.cn/f/article/detail?id=206
> 
> 根据我实践来看，屏蔽这个并没有发现有什么异常，建议在本地拦截掉这个域名（比如Windows的Hosts/浏览器插件、iOS的ShadowRocket/Adguard、安装的Clash/Adguard）
> 
> 类似的还有
> 
> 1. dataflow.bilibili.com
> 2. cm.bilibili.com
> 
> 等没明显功能，杀了没影响的
> 
> 既不会影响哔哩哔哩客户端和网页版使用，但是却在高配请求
> 
> 要不要放行自己考虑，可自己加白

不知道为什么最近又有人拿这个事情炒作，讲道理这个贴是搜索这个域名后谷歌默认的第一个结果

data.bilibili.com 是交互行为上报域名，和 spider-tracker.xiaohongshu.com等log域名效果一致。

不影响Ｂ站的全部功能，包括浏览记录、推荐算法、下发和访问pcdn、音视频播放、评论、投稿、广告推送、商城、会员等功能。

不过具体要看抓包，Ｂ站这类无用域名有好几个
