### ISSUE TITLE
错误拦截网址

### ISSUE THREAD

**Issue by Kings-Github** [BlueSkyXN/AdGuardHomeRules#27]
自己平时经常使用的矢量图下载网站错误拦截了，阿里巴巴的
https://www.iconfont.cn/

**Comment by Kings-Github** [comment]
规则使用的是：https://mirror.ghproxy.com/https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/all.txt

**Comment by Kings-Github** [comment]
也拦截网址：paypal.com
错误拦截网址太多了，不建议使用此项目......

**Comment by sonstar321** [comment]
同使用此规则，无你说的问题，查下其他问题，你可以添加作者提供的白名单，还有ADG可以查看是否真的拦截了，也可以手动解除拦截

**Comment by BlueSkyXN** [comment]
> 也拦截网址：paypal.com 错误拦截网址太多了，不建议使用此项目......

**https://github.com/BlueSkyXN/AdGuardHomeRules/edit/master/ok.txt**
第11、12行
