### ISSUE TITLE
存在误拦截

### ISSUE THREAD

**Issue by XuuKoo** [BlueSkyXN/AdGuardHomeRules#3]
https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/Shadowrocket/SKY-NOAD.conf

这里把整个雅虎的域名给拦截了：
DOMAIN-SUFFIX,yahoo.com,REJECT-200

同时，把这几个域名后缀整个拦截是值得商榷的：
DOMAIN-SUFFIX,fun,REJECT-200
DOMAIN-SUFFIX,biz,REJECT-200
DOMAIN-SUFFIX,club,REJECT-200
DOMAIN-SUFFIX,info,REJECT-200

**Comment by BlueSkyXN** [comment]
其实我是故意的，这几个域名99.9%都是广告
DOMAIN-SUFFIX,fun,REJECT-200
DOMAIN-SUFFIX,biz,REJECT-200
DOMAIN-SUFFIX,club,REJECT-200
DOMAIN-SUFFIX,info,REJECT-200
然后雅虎，最烂大街的广告供应商，又没人用，广告又多
不过，考虑了一下，稍后推出lite版本

**Comment by BlueSkyXN** [comment]
https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/Shadowrocket/SKY-NOAD-Lite.conf
如果还有拦截名单问题欢迎继续反馈哦
