### ISSUE TITLE
图片加载失败

### ISSUE THREAD

**Issue by AlieZero** [BlueSkyXN/AdGuardHomeRules#6]
使用rules后，百度搜索图片加载失败

**Comment by BlueSkyXN** [comment]
能F12、小火煎、ADH记录等方式查看到记录吗

**Comment by yizhitangtongxue** [comment]
同百度搜索图片加载失败

**Comment by BlueSkyXN** [comment]
> 同百度搜索图片加载失败

经过全局测试，在手机上使用百度搜索，打开官网和任意搜索关键字，均没有图片异常
ADH处仅屏蔽 hpd.baidu.com
请检查你受影响的域名
