### ISSUE TITLE
重复规则太多了，可以使用EMeditor去重复，去掉之后21.1M左右

### ISSUE THREAD

**Issue by jhsvip** [BlueSkyXN/AdGuardHomeRules#9]
另外很多被误杀的。。。需要自己手动慢慢搞了
比如QQ相册、百度的一些图片等等、、、

**Comment by BlueSkyXN** [comment]
百度和qq确实有点小毛病

**Comment by BlueSkyXN** [comment]
一般QQ是问题不大，百度由于有些域名比较怪，会被杀

**Comment by BlueSkyXN** [comment]
用Editplus做了去重，生成一个 all-dd.txt
有误杀的域名建议发出来方便加到白名单
